# Generated by Django 6.0.3 on 2026-04-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=225)),
                ('lastname', models.CharField(max_length=225)),
                ('username', models.CharField(max_length=225, unique=True)),
                ('password', models.CharField(max_length=225)),
            ],
        ),
    ]
