# Generated by Django 6.0.3 on 2026-04-04 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=10, unique=True),
        ),
    ]
